- name: <%= 'erb_' + 'element' %>
  contents:
  - name: text
    type: EssenceRichtext

- name: slide
  contents:
    - name: picture
      type: EssencePicture
    - name: caption
      type: EssenceText
      as_element_title: true

- name: slider
  nestable_elements:
    - slide

- name: gallery
  picture_gallery: true
